### ISSUE TITLE
error when running sarsa code

### ISSUE THREAD

**Issue by sinamcr7** [vojtamolda/reinforcement-learning-an-introduction#16]
when I try to run code for sansa it shows this error and I couldn't find any solution in the internet:

```
Traceback (most recent call last):
  File "\PycharmProjects\test_gym\main.py", line 59, in <module>
    q, policy, _ = sarsa(env, 500, eps0=0.5, alpha=0.5)
  File "\PycharmProjects\test_gym\sarsa.py", line 57, in sarsa
    next_state, reward, done, _, info = env.step(action)
  File "\anaconda3\envs\gym\lib\site-packages\gym\wrappers\time_limit.py", line 50, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
ValueError: not enough values to unpack (expected 5, got 4)

Process finished with exit code 1
```

please help me fix this

**Comment by vojtamolda** [comment]
Can you, please, provide me with a way to reproduce it? I'm not sure what script you're running and how.

**Comment by vojtamolda** [comment]
I'm closing this as a stale issue, since I don't have a way to reproduce.
